services:
  db:
    image: postgis/postgis:13-3.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: gis
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d gis" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  kafka:
    image: bitnami/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: 18000
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 18000
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - app-network

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - app-network

  backend1:
    build: ./backend1
    command: >
      sh -c "python manage.py migrate &&
            daphne -b 0.0.0.0 -p 8000 backend1.asgi:application"
    volumes:
      - ./backend1:/app
    ports:
      - "8800:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_started
    networks:
      - app-network

  backend2:
    build: ./backend2
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./backend2:/app
    ports:
      - "8801:8001"
    depends_on:
      - backend1
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend1
    networks:
      - app-network

  celery1:
    build: ./backend1
    command: celery -A backend1 worker --loglevel=info -Q backend1_queue
    volumes:
      - ./backend1:/app
    depends_on:
      - backend1
    networks:
      - app-network

  celery2:
    build: ./backend2
    command: celery -A backend2 worker --loglevel=info -Q backend2_queue
    volumes:
      - ./backend2:/app
    depends_on:
      - backend2
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5550:80"
    depends_on:
      - db
    networks:
      - app-network

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      API_URL: http://localhost:8000/swagger.json
    networks:
      - app-network

  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5004:5044"
    volumes:
      - ./config/elk/logstash/config/logstash.conf:/etc/logstash/conf.d/logstash.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge